### ISSUE TITLE
Root setting doesn't seem to be working.

### ISSUE THREAD

**Issue by paxperscientiam** [remiprev/teamocil#101] opened 2015-11-12 01:15 UTC
Let me preface this by saying that I new to tmux.

Okay, so I'm going through the teamocil sample configurations and it seems that the root option is not respected. No matter which directory I set "root" to, it always sets the working directory of each pane to HOME.

Also, starting commands are run multiple times. Or at least printed multiple times. Is it supposed to do that?

![screen shot 2015-11-11 at 8 11 48 pm](https://cloud.githubusercontent.com/assets/7539871/11107961/9a07d374-88b0-11e5-9fb1-c285075e394d.png)

[yml.txt](https://github.com/remiprev/teamocil/files/32473/yml.txt)

**Comment by remiprev** [comment] 2015-11-15 16:02
Can you run `teamocil --debug layout_name` and paste the output here? Can you also specify which version of tmux (`tmux -V`) and teamocil (`teamocil --version`) you’re running?

Thank you!

**Comment by paxperscientiam** [comment] 2015-11-16 14:29
Hello remiprev,

`tmux -V` yields `tmux 2.1`

`teamocil --version` yields `1.3.1`

Running `teamocil --debug sample` yields the following:

{{{
no server running on /private/var/folders/4f/kp7v_nls1q3dldw9kql4r47c0000gq/T/tmux-503/default
tmux rename-session 'teamocil-session-944286'
tmux new-window -n 'sample-two-panes' -c '/Users/cdr35/Desktop'
tmux send-keys -t 'sample-two-panes.0' 'echo "Shalom"'
tmux send-keys -t 'sample-two-panes.0' 'Enter'
tmux select-layout -t 'sample-two-panes' 'even-horizontal'
tmux split-window -t 'sample-two-panes' -c '/Users/cdr35/Desktop'
tmux send-keys -t 'sample-two-panes.1' 'echo "Yo"'
tmux send-keys -t 'sample-two-panes.1' 'Enter'
tmux select-layout -t 'sample-two-panes' 'even-horizontal'
tmux select-pane -t sample-two-panes.0
}}}

And here's sample.yml
{{{
windows:
  - name: sample-two-panes
    root: /Users/cdr35/Desktop
    layout: even-horizontal
    panes:
      - echo "Shalom"
      - echo "Yo"
}}}

**Comment by remiprev** [comment] 2015-11-19 11:44
I’m not sure what the expected result is. I have the same debug output as you and the result is :

```
.------------------.------------------.
| Shalom           | Yo               |
|                  |                  |
|                  |                  |
|                  |                  |
|                  |                  |
|                  |                  |
|                  |                  |
|                  |                  |
|                  |                  |
'------------------'------------------'
```

What is your result?

**Comment by paxperscientiam** [comment] 2015-11-23 13:57
Good morning, remiprev!

Yes, I get the correct pane breakdown and the echo output works just fine. However, the PWD of each pane is $HOME and not the directory set by the root attribute in the teamocil file.

Isn't that desired behavior, or am I misunderstanding?

**Comment by remiprev** [comment] 2015-11-23 21:37
> Isn't that desired behavior, or am I misunderstanding?

Indeed, this is not the desired behavior. The `-c '/Users/cdr35/Desktop'` option tells tmux to open a new window and to set its root to `'/Users/cdr35/Desktop'`.

Can you try to run this command anywhere in tmux?

```bash
$ tmux new-window -n 'test' -c '/Users/cdr35/Desktop'
```

If this launches a new window but its `pwd` is still `$HOME`, we’ll have to assume that this is not a bug in `teamocil` but maybe with `tmux` itself or maybe by a custom shell script that sets your `pwd` on each new session.

**Comment by Taluu** [comment] 2015-11-23 23:34
I also have this problem... But it is only in the main panel. So if I take your example (two panels), then the main panel (the one on the left) will be left witgh the $HOME direcotry while the seocnd one in set to the correct directory.

I guess this is more a tmux problem ?

**Comment by paxperscientiam** [comment] 2015-11-24 01:17
@remiprev @Taluu 

Yeah, this now looks like a tmux problem.
```
$ tmux new-window -n 'test' -c '/Users/cdr35/Desktop'
```
The 'c' flag seems to be ignored by tmux. So, perhaps this is a tmux problem afterall. At least a problem with tmux 2.1, the version I'm using. :/

 @Taluu can you show a minimal working sample teamocil file that reproduces the behavior cited in your post?

**Comment by paxperscientiam** [comment] 2015-11-24 01:35
OK, I am ashamed to admit this, but my .bash_profile had a 'cd ~' command buried deep within it. Mystery solved. Ugh.

Thanks for humoring me, remiprev

**Comment by remiprev** [comment] 2015-11-24 13:14
Ah, that’s what I thought, no worries! :smile: 

@Taluu I’ll wait for your feedback before closing this issue. Can you try to reproduce the behavior by just running these commands :

```bash
$ tmux new-window -n 'test' -c '/path/to/directory'
$ tmux split-window
```

Both panes should have their `pwd` set to `'/path/to/directory'`.

**Comment by Taluu** [comment] 2015-11-25 09:45
They do have the same pwd, which is set to the right path

**Comment by Taluu** [comment] 2015-11-25 10:07
And if it helps, I have two errors on the main panel (the one where the pwd is not correct) : `can't find window CLIs`, two times

**Comment by Taluu** [comment] 2016-05-16 09:57
If it helps, here is a reproduction of the problem with another (simple) config file, and the debug output ;

```yml
name: Debug
windows:
  - name: CLIs
    root: ~/dev/
    focus: true
    panes:
      - commands: ["cd Totem", "nvm use 5.9"]
      - tail -f /var/log/php.log
      - commands: ["cd symfony", "nvm use 5.9"]

  - name: CLIs2
    root: ~/dev/
    focus: true
    panes:
      - commands: ["cd Totem", "nvm use 5.9"]
      - tail -f /var/log/php.log
      - commands: ["cd symfony", "nvm use 5.9"]
```

```
tmux rename-session 'Debug'
tmux send-keys -t 'CLIs.0' 'cd "/home/talus/dev"'
tmux send-keys -t 'CLIs.0' 'Enter'
tmux rename-window 'CLIs'
tmux send-keys -t 'CLIs.0' 'cd Totem; nvm use 5.9'
tmux send-keys -t 'CLIs.0' 'Enter'
tmux split-window -t 'CLIs' -c '/home/talus/dev'
tmux send-keys -t 'CLIs.1' 'tail -f /var/log/php.log'
tmux send-keys -t 'CLIs.1' 'Enter'
tmux split-window -t 'CLIs' -c '/home/talus/dev'
tmux send-keys -t 'CLIs.2' 'cd symfony; nvm use 5.9'
tmux send-keys -t 'CLIs.2' 'Enter'
tmux select-pane -t CLIs.0
tmux new-window -n 'CLIs2' -c '/home/talus/dev'
tmux send-keys -t 'CLIs2.0' 'cd Totem; nvm use 5.9'
tmux send-keys -t 'CLIs2.0' 'Enter'
tmux split-window -t 'CLIs2' -c '/home/talus/dev'
tmux send-keys -t 'CLIs2.1' 'tail -f /var/log/php.log'
tmux send-keys -t 'CLIs2.1' 'Enter'
tmux split-window -t 'CLIs2' -c '/home/talus/dev'
tmux send-keys -t 'CLIs2.2' 'cd symfony; nvm use 5.9'
tmux send-keys -t 'CLIs2.2' 'Enter'
tmux select-pane -t CLIs2.0
tmux select-window -t 0
```

And I have two times the message "Can't find window CLIs", and it doesn't change my directory to the root on the first pane of the first window (the other windows are fine though).

As you can see, it seems the renaming of the first window seems to happen _after_ the creation of the first pane.

Using tmux 2.2 with Teamocil 1.4.1

(Yeah this acts as a "UP" :D)

**Comment by remiprev** [comment] 2016-05-16 10:03
Are you sure you’re running Teamocil 1.4.1? Here’s my `--debug` output from the same layout file:

```
tmux rename-session 'Debug'
tmux new-window -n 'CLIs' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs.100' 'cd Totem; nvm use 5.9'
tmux send-keys -t 'CLIs.100' 'Enter'
tmux split-window -t 'CLIs' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs.101' 'tail -f /var/log/php.log'
tmux send-keys -t 'CLIs.101' 'Enter'
tmux split-window -t 'CLIs' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs.102' 'cd symfony; nvm use 5.9'
tmux send-keys -t 'CLIs.102' 'Enter'
tmux select-pane -t CLIs.100
tmux new-window -n 'CLIs2' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs2.100' 'cd Totem; nvm use 5.9'
tmux send-keys -t 'CLIs2.100' 'Enter'
tmux split-window -t 'CLIs2' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs2.101' 'tail -f /var/log/php.log'
tmux send-keys -t 'CLIs2.101' 'Enter'
tmux split-window -t 'CLIs2' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs2.102' 'cd symfony; nvm use 5.9'
tmux send-keys -t 'CLIs2.102' 'Enter'
tmux select-pane -t CLIs2.100
tmux select-window -t 4
```

However, if I run it with `--debug --here`:

```
tmux rename-session 'Debug'
tmux send-keys -t 'CLIs.100' 'cd "/Users/remi/dev"'
tmux send-keys -t 'CLIs.100' 'Enter'
tmux rename-window 'CLIs'
tmux send-keys -t 'CLIs.100' 'cd Totem; nvm use 5.9'
tmux send-keys -t 'CLIs.100' 'Enter'
tmux split-window -t 'CLIs' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs.101' 'tail -f /var/log/php.log'
tmux send-keys -t 'CLIs.101' 'Enter'
tmux split-window -t 'CLIs' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs.102' 'cd symfony; nvm use 5.9'
tmux send-keys -t 'CLIs.102' 'Enter'
tmux select-pane -t CLIs.100
tmux new-window -n 'CLIs2' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs2.100' 'cd Totem; nvm use 5.9'
tmux send-keys -t 'CLIs2.100' 'Enter'
tmux split-window -t 'CLIs2' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs2.101' 'tail -f /var/log/php.log'
tmux send-keys -t 'CLIs2.101' 'Enter'
tmux split-window -t 'CLIs2' -c '/Users/remi/dev'
tmux send-keys -t 'CLIs2.102' 'cd symfony; nvm use 5.9'
tmux send-keys -t 'CLIs2.102' 'Enter'
tmux select-pane -t CLIs2.100
tmux select-window -t 3
```

So there still seems to be a problem here :/

**Comment by remiprev** [comment] 2016-05-16 10:10
Oh well, #110 solves the problem! I’m going to close the issue.

**Closed by remiprev** 2016-05-16 10:10 UTC
Labels: waiting-for-op
